apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: greenpay-external-secret
  namespace: greenpay
  labels:
    app.kubernetes.io/name: greenpay
    app.kubernetes.io/part-of: greenpay
    app.kubernetes.io/component: secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: greenpay-secret-store
    kind: SecretStore
  target:
    name: greenpay-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: greenpay/credentials
