apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greenpay-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- include "greenpay.ingress.tlsAnnotations" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- include "greenpay.ingress.tls" . | nindent 2 }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: {{ .Values.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: {{ .Values.frontend.port }}
